<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMqeVmkK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMqeVmkK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMqeVmkK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMqeVmkK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMqeVmkK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MqeVmkK',
    'container.build_id' => '9564128d',
    'container.build_time' => 1651759148,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMqeVmkK');
